const JEST_EXTENDED_TIMEOUT = 30000;

const EXISTING_CATEGORY = 'mens-clothing-jackets';
const EXISTING_PARENT_CATEGORY = 'mens';
const UNEXISTING_CATEGORY = 'i-do-not-exist';

const EXISTING_ITEM_ID = '25565189';
const EXISTING_ITEM_VARIANT_ID = '701643540020';
const UNEXISTING_ITEM_ID = 'this-id-does-not-exist';

const REGISTERED_NAME = 'aaa';
const REGISTERED_EMAIL = 'aaa@gmail.com';
const REGISTERED_PASSWORD = '123456';
const UNEXISTING_EMAIL = 'i-do-not-exist@gmail.com';

module.exports = {
  JEST_EXTENDED_TIMEOUT,
  EXISTING_CATEGORY,
  EXISTING_PARENT_CATEGORY,
  UNEXISTING_CATEGORY,
  EXISTING_ITEM_ID,
  EXISTING_ITEM_VARIANT_ID,
  UNEXISTING_ITEM_ID,
  REGISTERED_NAME,
  REGISTERED_EMAIL,
  REGISTERED_PASSWORD,
  UNEXISTING_EMAIL,
};
